/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Database": {
      "type": "sst.cloudflare.D1"
    }
    "DatabaseWorker": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "DatabaseWorkerSecret": {
      "type": "random.index/randomString.RandomString"
      "value": string
    }
    "FilesBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "FilesRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "Trpc": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
